[package]
name = "queries"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk4 = "0.4"
sourceview5 = { version = "0.4" }
libadwaita = "0.1.0-beta-1"
postgres = { version = "0.19.4", features = [ "with-chrono-0_4", "with-serde_json-1" ] }
postgres-openssl = "0.5.0"
postgres-native-tls = "0.5.0"
tokio = { version = "1.21.1", features=["rt", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.7", features = ["with-chrono-0_4", "with-serde_json-1"] }
futures = "0.3.24"
futures-util="0.3"
openssl = "0.10.41"
native-tls = "0.2"
sqlparser = "0.25.0"
regex = { version = "1.4.2" }
rusqlite = { version="0.24.2", features=["load_extension", "csvtab", "vtab", "functions", "serde_json", "backup", "column_decltype" ], optional=true }
rust_decimal = { version = "1.10.1", features = ["db-postgres"] }
serde = { version="1.0.130", features=["derive"] }
serde_json = "1.0.68"
itertools = "0.10"
csv = "1.1.3"
num-traits="0.2.14"
quick-xml = "0.23.0"
either = "1.6.1"
papyri = { git = "https://github.com/limads/papyri.git", features=["gdk4", "gdk-pixbuf", "cairo-rs"] }
notify = "4.0.17"
chrono = "0.4.19"
once_cell = "1.9.0"
anyhow = "1.0"
ordinal = "0.2"
base64 = "0.13.0"
stateful =  { git="https://github.com/limads/stateful.git" }
archiver = { git="https://github.com/limads/archiver.git" }
log = "0.4.17"
# systemd-journal-logger = "0.5.0"
rand = "0.8.5"

[[bin]]
name="queries"
path="src/main.rs"

[build-dependencies]
gtk4 = "0.4"

